//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfaceDataToDb.DdService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DdService.DdServiceSoap")]
    public interface DdServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YzUP", ReplyAction="*")]
        InterfaceDataToDb.DdService.YzUPResponse YzUP(InterfaceDataToDb.DdService.YzUPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YzUP", ReplyAction="*")]
        System.Threading.Tasks.Task<InterfaceDataToDb.DdService.YzUPResponse> YzUPAsync(InterfaceDataToDb.DdService.YzUPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YzUPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YzUP", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.DdService.YzUPRequestBody Body;
        
        public YzUPRequest() {
        }
        
        public YzUPRequest(InterfaceDataToDb.DdService.YzUPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class YzUPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passWord;
        
        public YzUPRequestBody() {
        }
        
        public YzUPRequestBody(string userName, string passWord) {
            this.userName = userName;
            this.passWord = passWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YzUPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YzUPResponse", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.DdService.YzUPResponseBody Body;
        
        public YzUPResponse() {
        }
        
        public YzUPResponse(InterfaceDataToDb.DdService.YzUPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class YzUPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string YzUPResult;
        
        public YzUPResponseBody() {
        }
        
        public YzUPResponseBody(string YzUPResult) {
            this.YzUPResult = YzUPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DdServiceSoapChannel : InterfaceDataToDb.DdService.DdServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DdServiceSoapClient : System.ServiceModel.ClientBase<InterfaceDataToDb.DdService.DdServiceSoap>, InterfaceDataToDb.DdService.DdServiceSoap {
        
        public DdServiceSoapClient() {
        }
        
        public DdServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DdServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DdServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DdServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfaceDataToDb.DdService.YzUPResponse InterfaceDataToDb.DdService.DdServiceSoap.YzUP(InterfaceDataToDb.DdService.YzUPRequest request) {
            return base.Channel.YzUP(request);
        }
        
        public string YzUP(string userName, string passWord) {
            InterfaceDataToDb.DdService.YzUPRequest inValue = new InterfaceDataToDb.DdService.YzUPRequest();
            inValue.Body = new InterfaceDataToDb.DdService.YzUPRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            InterfaceDataToDb.DdService.YzUPResponse retVal = ((InterfaceDataToDb.DdService.DdServiceSoap)(this)).YzUP(inValue);
            return retVal.Body.YzUPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfaceDataToDb.DdService.YzUPResponse> InterfaceDataToDb.DdService.DdServiceSoap.YzUPAsync(InterfaceDataToDb.DdService.YzUPRequest request) {
            return base.Channel.YzUPAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfaceDataToDb.DdService.YzUPResponse> YzUPAsync(string userName, string passWord) {
            InterfaceDataToDb.DdService.YzUPRequest inValue = new InterfaceDataToDb.DdService.YzUPRequest();
            inValue.Body = new InterfaceDataToDb.DdService.YzUPRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            return ((InterfaceDataToDb.DdService.DdServiceSoap)(this)).YzUPAsync(inValue);
        }
    }
}
