//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfaceDataToDb.ServiceLdzz {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLdzz.LdzzWebServiceSoap")]
    public interface LdzzWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 year 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_de", ReplyAction="*")]
        InterfaceDataToDb.ServiceLdzz.Ldzz_deResponse Ldzz_de(InterfaceDataToDb.ServiceLdzz.Ldzz_deRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_de", ReplyAction="*")]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_deResponse> Ldzz_deAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_deRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 xzqhCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_TjByXzqh", ReplyAction="*")]
        InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhResponse Ldzz_TjByXzqh(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_TjByXzqh", ReplyAction="*")]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhResponse> Ldzz_TjByXzqhAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 xzqhCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_TjByLdlx", ReplyAction="*")]
        InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxResponse Ldzz_TjByLdlx(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_TjByLdlx", ReplyAction="*")]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxResponse> Ldzz_TjByLdlxAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 xzqhCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_TjByZdgn", ReplyAction="*")]
        InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnResponse Ldzz_TjByZdgn(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_TjByZdgn", ReplyAction="*")]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnResponse> Ldzz_TjByZdgnAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 year 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_TaizhangCX", ReplyAction="*")]
        InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXResponse Ldzz_TaizhangCX(InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_TaizhangCX", ReplyAction="*")]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXResponse> Ldzz_TaizhangCXAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 xzqhCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_XmlbByXzqh", ReplyAction="*")]
        InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhResponse Ldzz_XmlbByXzqh(InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_XmlbByXzqh", ReplyAction="*")]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhResponse> Ldzz_XmlbByXzqhAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 applicationid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_SqbByCode", ReplyAction="*")]
        InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeResponse Ldzz_SqbByCode(InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_SqbByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeResponse> Ldzz_SqbByCodeAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 applicationid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_DjbByCode", ReplyAction="*")]
        InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeResponse Ldzz_DjbByCode(InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ldzz_DjbByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeResponse> Ldzz_DjbByCodeAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_deRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_de", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_deRequestBody Body;
        
        public Ldzz_deRequest() {
        }
        
        public Ldzz_deRequest(InterfaceDataToDb.ServiceLdzz.Ldzz_deRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_deRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string year;
        
        public Ldzz_deRequestBody() {
        }
        
        public Ldzz_deRequestBody(string year) {
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_deResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_deResponse", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_deResponseBody Body;
        
        public Ldzz_deResponse() {
        }
        
        public Ldzz_deResponse(InterfaceDataToDb.ServiceLdzz.Ldzz_deResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_deResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ldzz_deResult;
        
        public Ldzz_deResponseBody() {
        }
        
        public Ldzz_deResponseBody(string Ldzz_deResult) {
            this.Ldzz_deResult = Ldzz_deResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_TjByXzqhRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_TjByXzqh", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhRequestBody Body;
        
        public Ldzz_TjByXzqhRequest() {
        }
        
        public Ldzz_TjByXzqhRequest(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_TjByXzqhRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xzqhCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime startTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime endTime;
        
        public Ldzz_TjByXzqhRequestBody() {
        }
        
        public Ldzz_TjByXzqhRequestBody(string xzqhCode, System.DateTime startTime, System.DateTime endTime) {
            this.xzqhCode = xzqhCode;
            this.startTime = startTime;
            this.endTime = endTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_TjByXzqhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_TjByXzqhResponse", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhResponseBody Body;
        
        public Ldzz_TjByXzqhResponse() {
        }
        
        public Ldzz_TjByXzqhResponse(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_TjByXzqhResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ldzz_TjByXzqhResult;
        
        public Ldzz_TjByXzqhResponseBody() {
        }
        
        public Ldzz_TjByXzqhResponseBody(string Ldzz_TjByXzqhResult) {
            this.Ldzz_TjByXzqhResult = Ldzz_TjByXzqhResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_TjByLdlxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_TjByLdlx", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxRequestBody Body;
        
        public Ldzz_TjByLdlxRequest() {
        }
        
        public Ldzz_TjByLdlxRequest(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_TjByLdlxRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xzqhCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime startTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime endTime;
        
        public Ldzz_TjByLdlxRequestBody() {
        }
        
        public Ldzz_TjByLdlxRequestBody(string xzqhCode, System.DateTime startTime, System.DateTime endTime) {
            this.xzqhCode = xzqhCode;
            this.startTime = startTime;
            this.endTime = endTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_TjByLdlxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_TjByLdlxResponse", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxResponseBody Body;
        
        public Ldzz_TjByLdlxResponse() {
        }
        
        public Ldzz_TjByLdlxResponse(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_TjByLdlxResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ldzz_TjByLdlxResult;
        
        public Ldzz_TjByLdlxResponseBody() {
        }
        
        public Ldzz_TjByLdlxResponseBody(string Ldzz_TjByLdlxResult) {
            this.Ldzz_TjByLdlxResult = Ldzz_TjByLdlxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_TjByZdgnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_TjByZdgn", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnRequestBody Body;
        
        public Ldzz_TjByZdgnRequest() {
        }
        
        public Ldzz_TjByZdgnRequest(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_TjByZdgnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xzqhCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime startTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime endTime;
        
        public Ldzz_TjByZdgnRequestBody() {
        }
        
        public Ldzz_TjByZdgnRequestBody(string xzqhCode, System.DateTime startTime, System.DateTime endTime) {
            this.xzqhCode = xzqhCode;
            this.startTime = startTime;
            this.endTime = endTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_TjByZdgnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_TjByZdgnResponse", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnResponseBody Body;
        
        public Ldzz_TjByZdgnResponse() {
        }
        
        public Ldzz_TjByZdgnResponse(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_TjByZdgnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ldzz_TjByZdgnResult;
        
        public Ldzz_TjByZdgnResponseBody() {
        }
        
        public Ldzz_TjByZdgnResponseBody(string Ldzz_TjByZdgnResult) {
            this.Ldzz_TjByZdgnResult = Ldzz_TjByZdgnResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_TaizhangCXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_TaizhangCX", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXRequestBody Body;
        
        public Ldzz_TaizhangCXRequest() {
        }
        
        public Ldzz_TaizhangCXRequest(InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_TaizhangCXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string year;
        
        public Ldzz_TaizhangCXRequestBody() {
        }
        
        public Ldzz_TaizhangCXRequestBody(string year) {
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_TaizhangCXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_TaizhangCXResponse", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXResponseBody Body;
        
        public Ldzz_TaizhangCXResponse() {
        }
        
        public Ldzz_TaizhangCXResponse(InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_TaizhangCXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ldzz_TaizhangCXResult;
        
        public Ldzz_TaizhangCXResponseBody() {
        }
        
        public Ldzz_TaizhangCXResponseBody(string Ldzz_TaizhangCXResult) {
            this.Ldzz_TaizhangCXResult = Ldzz_TaizhangCXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_XmlbByXzqhRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_XmlbByXzqh", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhRequestBody Body;
        
        public Ldzz_XmlbByXzqhRequest() {
        }
        
        public Ldzz_XmlbByXzqhRequest(InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_XmlbByXzqhRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xzqhCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime startTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime endTime;
        
        public Ldzz_XmlbByXzqhRequestBody() {
        }
        
        public Ldzz_XmlbByXzqhRequestBody(string xzqhCode, System.DateTime startTime, System.DateTime endTime) {
            this.xzqhCode = xzqhCode;
            this.startTime = startTime;
            this.endTime = endTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_XmlbByXzqhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_XmlbByXzqhResponse", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhResponseBody Body;
        
        public Ldzz_XmlbByXzqhResponse() {
        }
        
        public Ldzz_XmlbByXzqhResponse(InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_XmlbByXzqhResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ldzz_XmlbByXzqhResult;
        
        public Ldzz_XmlbByXzqhResponseBody() {
        }
        
        public Ldzz_XmlbByXzqhResponseBody(string Ldzz_XmlbByXzqhResult) {
            this.Ldzz_XmlbByXzqhResult = Ldzz_XmlbByXzqhResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_SqbByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_SqbByCode", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeRequestBody Body;
        
        public Ldzz_SqbByCodeRequest() {
        }
        
        public Ldzz_SqbByCodeRequest(InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_SqbByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applicationid;
        
        public Ldzz_SqbByCodeRequestBody() {
        }
        
        public Ldzz_SqbByCodeRequestBody(string applicationid) {
            this.applicationid = applicationid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_SqbByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_SqbByCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeResponseBody Body;
        
        public Ldzz_SqbByCodeResponse() {
        }
        
        public Ldzz_SqbByCodeResponse(InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_SqbByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ldzz_SqbByCodeResult;
        
        public Ldzz_SqbByCodeResponseBody() {
        }
        
        public Ldzz_SqbByCodeResponseBody(string Ldzz_SqbByCodeResult) {
            this.Ldzz_SqbByCodeResult = Ldzz_SqbByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_DjbByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_DjbByCode", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeRequestBody Body;
        
        public Ldzz_DjbByCodeRequest() {
        }
        
        public Ldzz_DjbByCodeRequest(InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_DjbByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applicationid;
        
        public Ldzz_DjbByCodeRequestBody() {
        }
        
        public Ldzz_DjbByCodeRequestBody(string applicationid) {
            this.applicationid = applicationid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ldzz_DjbByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ldzz_DjbByCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeResponseBody Body;
        
        public Ldzz_DjbByCodeResponse() {
        }
        
        public Ldzz_DjbByCodeResponse(InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ldzz_DjbByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ldzz_DjbByCodeResult;
        
        public Ldzz_DjbByCodeResponseBody() {
        }
        
        public Ldzz_DjbByCodeResponseBody(string Ldzz_DjbByCodeResult) {
            this.Ldzz_DjbByCodeResult = Ldzz_DjbByCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LdzzWebServiceSoapChannel : InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LdzzWebServiceSoapClient : System.ServiceModel.ClientBase<InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap>, InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap {
        
        public LdzzWebServiceSoapClient() {
        }
        
        public LdzzWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LdzzWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LdzzWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LdzzWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfaceDataToDb.ServiceLdzz.Ldzz_deResponse InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_de(InterfaceDataToDb.ServiceLdzz.Ldzz_deRequest request) {
            return base.Channel.Ldzz_de(request);
        }
        
        public string Ldzz_de(string year) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_deRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_deRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_deRequestBody();
            inValue.Body.year = year;
            InterfaceDataToDb.ServiceLdzz.Ldzz_deResponse retVal = ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_de(inValue);
            return retVal.Body.Ldzz_deResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_deResponse> InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_deAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_deRequest request) {
            return base.Channel.Ldzz_deAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_deResponse> Ldzz_deAsync(string year) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_deRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_deRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_deRequestBody();
            inValue.Body.year = year;
            return ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_deAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhResponse InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_TjByXzqh(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhRequest request) {
            return base.Channel.Ldzz_TjByXzqh(request);
        }
        
        public string Ldzz_TjByXzqh(string xzqhCode, System.DateTime startTime, System.DateTime endTime) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhRequestBody();
            inValue.Body.xzqhCode = xzqhCode;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhResponse retVal = ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_TjByXzqh(inValue);
            return retVal.Body.Ldzz_TjByXzqhResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhResponse> InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_TjByXzqhAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhRequest request) {
            return base.Channel.Ldzz_TjByXzqhAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhResponse> Ldzz_TjByXzqhAsync(string xzqhCode, System.DateTime startTime, System.DateTime endTime) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_TjByXzqhRequestBody();
            inValue.Body.xzqhCode = xzqhCode;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            return ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_TjByXzqhAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxResponse InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_TjByLdlx(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxRequest request) {
            return base.Channel.Ldzz_TjByLdlx(request);
        }
        
        public string Ldzz_TjByLdlx(string xzqhCode, System.DateTime startTime, System.DateTime endTime) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxRequestBody();
            inValue.Body.xzqhCode = xzqhCode;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxResponse retVal = ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_TjByLdlx(inValue);
            return retVal.Body.Ldzz_TjByLdlxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxResponse> InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_TjByLdlxAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxRequest request) {
            return base.Channel.Ldzz_TjByLdlxAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxResponse> Ldzz_TjByLdlxAsync(string xzqhCode, System.DateTime startTime, System.DateTime endTime) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_TjByLdlxRequestBody();
            inValue.Body.xzqhCode = xzqhCode;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            return ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_TjByLdlxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnResponse InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_TjByZdgn(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnRequest request) {
            return base.Channel.Ldzz_TjByZdgn(request);
        }
        
        public string Ldzz_TjByZdgn(string xzqhCode, System.DateTime startTime, System.DateTime endTime) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnRequestBody();
            inValue.Body.xzqhCode = xzqhCode;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnResponse retVal = ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_TjByZdgn(inValue);
            return retVal.Body.Ldzz_TjByZdgnResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnResponse> InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_TjByZdgnAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnRequest request) {
            return base.Channel.Ldzz_TjByZdgnAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnResponse> Ldzz_TjByZdgnAsync(string xzqhCode, System.DateTime startTime, System.DateTime endTime) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_TjByZdgnRequestBody();
            inValue.Body.xzqhCode = xzqhCode;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            return ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_TjByZdgnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXResponse InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_TaizhangCX(InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXRequest request) {
            return base.Channel.Ldzz_TaizhangCX(request);
        }
        
        public string Ldzz_TaizhangCX(string year) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXRequestBody();
            inValue.Body.year = year;
            InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXResponse retVal = ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_TaizhangCX(inValue);
            return retVal.Body.Ldzz_TaizhangCXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXResponse> InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_TaizhangCXAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXRequest request) {
            return base.Channel.Ldzz_TaizhangCXAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXResponse> Ldzz_TaizhangCXAsync(string year) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_TaizhangCXRequestBody();
            inValue.Body.year = year;
            return ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_TaizhangCXAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhResponse InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_XmlbByXzqh(InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhRequest request) {
            return base.Channel.Ldzz_XmlbByXzqh(request);
        }
        
        public string Ldzz_XmlbByXzqh(string xzqhCode, System.DateTime startTime, System.DateTime endTime) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhRequestBody();
            inValue.Body.xzqhCode = xzqhCode;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhResponse retVal = ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_XmlbByXzqh(inValue);
            return retVal.Body.Ldzz_XmlbByXzqhResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhResponse> InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_XmlbByXzqhAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhRequest request) {
            return base.Channel.Ldzz_XmlbByXzqhAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhResponse> Ldzz_XmlbByXzqhAsync(string xzqhCode, System.DateTime startTime, System.DateTime endTime) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_XmlbByXzqhRequestBody();
            inValue.Body.xzqhCode = xzqhCode;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            return ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_XmlbByXzqhAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeResponse InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_SqbByCode(InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeRequest request) {
            return base.Channel.Ldzz_SqbByCode(request);
        }
        
        public string Ldzz_SqbByCode(string applicationid) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeRequestBody();
            inValue.Body.applicationid = applicationid;
            InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeResponse retVal = ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_SqbByCode(inValue);
            return retVal.Body.Ldzz_SqbByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeResponse> InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_SqbByCodeAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeRequest request) {
            return base.Channel.Ldzz_SqbByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeResponse> Ldzz_SqbByCodeAsync(string applicationid) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_SqbByCodeRequestBody();
            inValue.Body.applicationid = applicationid;
            return ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_SqbByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeResponse InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_DjbByCode(InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeRequest request) {
            return base.Channel.Ldzz_DjbByCode(request);
        }
        
        public string Ldzz_DjbByCode(string applicationid) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeRequestBody();
            inValue.Body.applicationid = applicationid;
            InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeResponse retVal = ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_DjbByCode(inValue);
            return retVal.Body.Ldzz_DjbByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeResponse> InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap.Ldzz_DjbByCodeAsync(InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeRequest request) {
            return base.Channel.Ldzz_DjbByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeResponse> Ldzz_DjbByCodeAsync(string applicationid) {
            InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeRequest inValue = new InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeRequest();
            inValue.Body = new InterfaceDataToDb.ServiceLdzz.Ldzz_DjbByCodeRequestBody();
            inValue.Body.applicationid = applicationid;
            return ((InterfaceDataToDb.ServiceLdzz.LdzzWebServiceSoap)(this)).Ldzz_DjbByCodeAsync(inValue);
        }
    }
}
